name: Install dependencies
description: Install dependencies
runs:
  using: composite
  steps:
    - name: Set Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set the site-packages environment variable
      run: python -c "import site; print(f'site_package_path={site.getsitepackages()[0]}')" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v2
      id: pip_cache
      with:
        path: ${{ env.site_package_path }}
        key: ${{ runner.os }}-pip-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}-12
    - uses: actions/cache@v2
      id: bin_cache
      with:
        path: /opt/hostedtoolcache/Python/3.6.15/x64/bin/
        key: ${{ runner.os }}-bin_cache-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}_2
