name: Github Actions test 1
on:
  push:
    branches:
      - main
jobs:
  Job1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: sudo apt install build-essential
      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-py3.6
      #     restore-keys: |
      #       ${{ runner.os }}-pip-py3.6
      - name: Install Python library
        run: pip install pandas==1.1.4
  # Job2:
  #   needs: Job1
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: Set Python version
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.6
  #     - uses: actions/cache@v2
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-py3.6
  #         restore-keys: |
  #           ${{ runner.os }}-pip-py3.6
  #     - name: Install Python library
  #       run: pip install pandas==1.1.4
  #     - run: pip freeze
