name: Github Actions test 1
on:
  push:
    branches:
      - main
jobs:
  Job1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: sudo apt install build-essential
      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - run: python -c "import site; print(f'site_package_path={site.getsitepackages()[0]}')" >> $GITHUB_ENV
      - run: echo ${{ env.site_package_path }}
      - uses: actions/cache@v2
        with:
          path: ${{ env.site_package_path }}
          key: ${{ runner.os }}-pip-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}
      # - run: pip install -r requirements.txt
      # /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages
      # - uses: actions/cache@v2
      #   with:
      #     path: /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages
      #     key: ${{ runner.os }}-pip-test1
      #     restore-keys: |
      #       ${{ runner.os }}-pip-${{ runner.os }}-pip-test1
