name: Github Actions test 1
on:
  push:
    branches:
      - main
jobs:
  Job1:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: sudo apt install build-essential
      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - run: python -c "import site; print(f'site_package_path={site.getsitepackages()[0]}')" >> $GITHUB_ENV
      - run: echo ${{ env.site_package_path }}
      - uses: actions/cache@v2
        id: pip_cache
        with:
          path: ${{ env.site_package_path }}
          key: ${{ runner.os }}-pip-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}-7
      - if: steps.pip_cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - run: echo which_flake8=`which flake8` >> $GITHUB_ENV
      - run: echo ${{ env.which_flake8 }}
      # - run: which -a mypy
      # - run: which -a numdoclint
      - uses: actions/cache@v2
        id: bin_cache
        with:
          path: /opt/hostedtoolcache/Python/3.6.15/x64/bin/
          key: ${{ runner.os }}-bin_cache-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}
  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - run: python -c "import site; print(f'site_package_path={site.getsitepackages()[0]}')" >> $GITHUB_ENV
      - uses: actions/cache@v2
        id: pip_cache
        with:
          path: ${{ env.site_package_path }}
          key: ${{ runner.os }}-pip-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}-7
      - uses: actions/cache@v2
        id: bin_cache
        with:
          path: /opt/hostedtoolcache/Python/3.6.15/x64/bin/
          key: ${{ runner.os }}-bin_cache-${{ env.site_package_path }}-${{ hashFiles('**/requirements.txt') }}
      - run: /opt/hostedtoolcache/Python/3.6.15/x64/bin/flake8 --help
